/*
 * Unitto is a calculator for Android
 * Copyright (c) 2025 Elshan Agaev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.sadellie.unitto.core.datastore

object PrefKeys {
  val THEMING_MODE_PREF_KEY = "THEMING_MODE_PREF_KEY"
  val ENABLE_DYNAMIC_THEME_PREF_KEY = "ENABLE_DYNAMIC_THEME_PREF_KEY"
  val ENABLE_AMOLED_THEME_PREF_KEY = "ENABLE_AMOLED_THEME_PREF_KEY"
  val CUSTOM_COLOR_PREF_KEY = "CUSTOM_COLOR_PREF_KEY"
  val MONET_MODE_PREF_KEY = "MONET_MODE_PREF_KEY"
  val STARTING_SCREEN_PREF_KEY = "STARTING_SCREEN_PREF_KEY"
  val ENABLE_TOOLS_EXPERIMENT_PREF_KEY = "ENABLE_TOOLS_EXPERIMENT_PREF_KEY"
  // val SYSTEM_FONT_PREF_KEY = "SYSTEM_FONT_PREF_KEY"
  val LAST_READ_CHANGELOG_PREF_KEY = "LAST_READ_CHANGELOG_PREF_KEY"
  val ENABLE_VIBRATIONS_PREF_KEY = "ENABLE_VIBRATIONS_PREF_KEY"
  val ENABLE_KEEP_SCREEN_ON_PREF_KEY = "ENABLE_KEEP_SCREEN_ON_PREF_KEY"
  val MIDDLE_ZERO_PREF_KEY = "MIDDLE_ZERO_PREF_KEY"
  val AC_BUTTON_PREF_KEY = "AC_BUTTON_PREF_KEY"
  // val RPN_MODE_PREF_KEY = "RPN_MODE_PREF_KEY"
  val DIGITS_PRECISION_PREF_KEY = "DIGITS_PRECISION_PREF_KEY"
  // val SEPARATOR_PREF_KEY = "SEPARATOR_PREF_KEY"
  val FORMATTER_GROUPING_PREF_KEY = "FORMATTER_GROUPING_PREF_KEY"
  val FORMATTER_FRACTIONAL_PREF_KEY = "FORMATTER_FRACTIONAL_PREF_KEY"
  val OUTPUT_FORMAT_PREF_KEY = "OUTPUT_FORMAT_PREF_KEY"
  val RADIAN_MODE_PREF_KEY = "RADIAN_MODE_PREF_KEY"
  val PARTIAL_HISTORY_VIEW_PREF_KEY = "PARTIAL_HISTORY_VIEW_PREF_KEY"
  val STEPPED_PARTIAL_HISTORY_VIEW_PREF_KEY = "STEPPED_PARTIAL_HISTORY_VIEW_PREF_KEY"
  val OPEN_HISTORY_VIEW_BUTTON_PREF_KEY = "OPEN_HISTORY_VIEW_BUTTON_PREF_KEY"
  val INITIAL_PARTIAL_HISTORY_VIEW_PREF_KEY = "INITIAL_PARTIAL_HISTORY_VIEW_PREF_KEY"
  val FRACTIONAL_OUTPUT_PREF_KEY = "FRACTIONAL_OUTPUT_PREF_KEY"
  val ADDITIONAL_BUTTONS_PREF_KEY = "ADDITIONAL_BUTTONS_PREF_KEY"
  val INVERSE_MODE_PREF_KEY = "INVERSE_MODE_PREF_KEY"
  val LATEST_LEFT_SIDE_PREF_KEY = "LATEST_LEFT_SIDE_PREF_KEY"
  val LATEST_RIGHT_SIDE_PREF_KEY = "LATEST_RIGHT_SIDE_PREF_KEY"
  val SHOWN_UNIT_GROUPS_PREF_KEY = "SHOWN_UNIT_GROUPS_PREF_KEY"
  val UNIT_CONVERTER_FAVORITES_ONLY_PREF_KEY = "UNIT_CONVERTER_FAVORITES_ONLY_PREF_KEY"
  val UNIT_CONVERTER_FORMAT_TIME_PREF_KEY = "UNIT_CONVERTER_FORMAT_TIME_PREF_KEY"
  val UNIT_CONVERTER_SORTING_PREF_KEY = "UNIT_CONVERTER_SORTING_PREF_KEY"
}
